#!/bin/bash

# PythonAnywhere Deployment (Alternative)
echo "🐍 Alternative: Deploy to PythonAnywhere"
echo "========================================"
echo ""
echo "🎯 **Free Python Hosting - Very Easy Setup:**"
echo ""
echo "1. 🌐 Go to: https://www.pythonanywhere.com"
echo "2. 📝 Create free account"
echo "3. 🔧 Upload your backend files"
echo "4. 🚀 Configure WSGI app"
echo ""
echo "📋 **Or use these working alternatives:**"
echo ""
echo "🟢 **Render**: https://render.com (recommended)"
echo "🔵 **Railway**: May still be building - check later"
echo "🟡 **Heroku**: heroku create your-app-name"
echo ""
echo "✅ **Current URLs to try:**"
echo "   Railway: https://detect-disease-with-fugaji-pro-production.up.railway.app"
echo ""
echo "🎯 **Quick Test Command:**"
echo "   curl https://detect-disease-with-fugaji-pro-production.up.railway.app/health"
