#!/bin/bash

# Alternative Backend Deployment - Using Render
echo "🚀 Deploying Amazing Kuku Backend to Render..."
echo "=============================================="

echo ""
echo "📋 **Manual Render Deployment Steps:**"
echo ""
echo "1. 🌐 Go to: https://render.com"
echo "2. 📝 Sign up/Login with GitHub"
echo "3. ➕ Click 'New' → 'Web Service'"
echo "4. 🔗 Connect repository: BINABASS091/amazing-kuku"
echo "5. ⚙️  Configure service:"
echo "   - Name: amazing-kuku-backend"
echo "   - Region: Choose closest to you"
echo "   - Branch: main"
echo "   - Root Directory: backend"
echo "   - Runtime: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python main.py"
echo "   - Instance Type: Free"
echo ""
echo "6. 🚀 Click 'Create Web Service'"
echo "7. ⏳ Wait for deployment (5-10 minutes)"
echo "8. 📋 Copy your service URL (will be like: https://amazing-kuku-backend.onrender.com)"
echo ""
echo "🎯 **After deployment, run:**"
echo "   ./update-backend-url.sh YOUR_RENDER_URL"
echo ""
echo "📚 **Alternative Quick Deploy Options:**"
echo ""
echo "🟦 **Vercel (Serverless):**"
echo "   vercel --prod"
echo ""
echo "🟨 **Heroku:**"
echo "   heroku create amazing-kuku-backend"
echo "   git subtree push --prefix backend heroku main"
echo ""
echo "🟪 **Railway (retry):**"
echo "   cd backend && railway up"
echo ""
echo "✅ **Current Railway URL (may work after build completes):**"
echo "   https://detect-disease-with-fugaji-pro-production.up.railway.app"
